[project]
frame_rate = 30
frame_range = []
exclude_from_batch = []

[calibration]
calibration_type = "calculate"

[pose]
pose_framework = "openpose"
pose_model = "BODY_25B"

[personAssociation]
single_person = true
tracked_keypoint = "Neck"
reproj_error_threshold_association = 20
likelihood_threshold_association = 0.2

[triangulation]
reproj_error_threshold_triangulation = 50
likelihood_threshold_triangulation = 0.3
min_cameras_for_triangulation = 2
interpolation = "cubic"
interp_if_gap_smaller_than = 10
show_interp_indices = true
handle_LR_swap = false
undistort_points = false
make_c3d = false

[filtering]
type = "butterworth"
display_figures = false

[opensim]
static_trial = [ "S00_P00_Participant/S00_P00_T00_StaticTrial",]
opensim_bin_path = "C:\\OpenSim 4.4\\bin"

[calibration.convert]
convert_from = "qualisys"

[filtering.butterworth]
order = 4
cut_off_frequency = 6

[filtering.kalman]
trust_ratio = 100
smooth = true

[filtering.butterworth_on_speed]
order = 4
cut_off_frequency = 10

[filtering.gaussian]
sigma_kernel = 2

[filtering.LOESS]
nb_values_used = 30

[filtering.median]
kernel_size = 9

[calibration.convert.qualisys]
binning_factor = 1

[calibration.convert.optitrack]

[calibration.calculate.intrinsics]
overwrite_intrinsics = true
show_detection_intrinsics = false
intrinsics_extension = "ppm"
extract_every_N_sec = 1
intrinsics_corners_nb = [ 9, 13,]
intrinsics_square_size = 30

[calibration.calculate.extrinsics]
calculate_extrinsics = true
extrinsics_method = "board"
moving_cameras = false

[calibration.calculate.extrinsics.board]
show_reprojection_error = true
extrinsics_extension = "ppm"
extrinsics_corners_nb = [ 9, 13,]
extrinsics_square_size = 170

[calibration.calculate.extrinsics.scene]
show_reprojection_error = true
extrinsics_extension = "ppm"
object_coords_3d = [ [ 0.0, 0.0, 0.0,], [ 0.0, 0.5, 0.0,], [ 0.0, 1.0, 0.0,], [ 0.0, 1.0, 0.515,], [ 0.0, 1.0, 1.002,], [ -1.5, 0.0, 0.0,], [ -1.0, 0.0, 0.0,], [ -0.4, 0.0, 0.0,], [ 0.405, 0.0, 0.0,], [ 1.005, 0.0, 0.0,], [ 1.505, 0.0, 0.0,],]

[calibration.calculate.extrinsics.keypoints]
